server:
  port: 8080

spring:
  application:
    name: Deposit Operations
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: rabbitmq.yml